#!/usr/bin/env bash
# Changing the redirection page
sudo apt-get update
sudo apt-get -y install nginx
touch /var/www/html/index.html
chmod 666 /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/server.name..;/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
