#!/usr/bin/env bash
# Script that prints from 0-12 hours and from 1-59 minutes
i=0
while (( i <= 12 ))
do
	echo "Hour: $i"
	j=1
	while (( j <= 59 ))
	do
		echo "$j"
		j=$(( j + 1 ))
	done
	i=$(( i + 1 ))
done
